### ISSUE TITLE
时间过滤能支持下between不？

### ISSUE THREAD

**Issue by xiaomingchen** [Baidu-ecom/bi-platform#112]
我刚改了些代码？就是会自动将时间条件自动转换成between，如果需要，我到时候给pull一个。。

**Comment by xiaomingchen** [comment]
修改以后，生成的SQL 类似  select DATE_FORMAT(created_at, "%Y%m%d") as created_at, pay_money, order_id from  order_info where  created_at between '20141101' and '20141231'

**Comment by wangyuxue** [comment]
已经支持
