### ISSUE TITLE
执行 mvn install 报错,用的是 maven 3.1.1

### ISSUE THREAD

**Issue by gemfirer** [Baidu-ecom/bi-platform#116]
[ERROR] Failed to execute goal on project tesseract: Could not resolve dependencies for project com.baidu.rigel.biplatform:tesseract:jar:1.3.1-RELEASE: The following artifacts could not be resolved: com.baidu.rigel.biplatform:cache:jar:1.3.1-RELEASE, com.baidu.rigel.biplatform:model:jar:1.3.1-RELEASE, com.baidu.rigel.biplatform:parser:jar:0.0.1-SNAPSHOT: Could not find artifact com.baidu.rigel.biplatform:cache:jar:1.3.1-RELEASE in central (http://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by wangyuxue** [comment]
已知晓，会尽快处理了

**Comment by gemfirer** [comment]
非常感谢！

**Comment by xiaomingchen** [comment]
install 的时候选择 bi-platform 进行install即可.

**Comment by gemfirer** [comment]
OK，构建成功！

**Comment by gemfirer** [comment]
有安装部署手册吗?又出现了一些问题，我想按照操作手册的步骤走一遍，😊

Date: Mon, 18 May 2015 23:10:54 -0700

**Comment by caoevan** [comment]
请问你是怎么构建的tesseract@ghost
