### ISSUE TITLE
designer 注册时

### ISSUE THREAD

**Issue by kisskevin** [Baidu-ecom/bi-platform#119]
java.net.UnknownHostException:后面是我填写的有效的邮箱地址

**Comment by wangyuxue** [comment]
你好，如果想完成designer的注册，需要在designer的application.properties中配置。具体参见博文：
http://my.oschina.net/biplatform/blog/412942。

**Comment by kisskevin** [comment]
就是按照这个配置的 ，邮件地址写的是我自己平时用的

**Comment by wangyuxue** [comment]
麻烦确认一下你配置的邮件服务器是否能够支持pop3的协议

**Comment by kisskevin** [comment]
问题解决了，用了新浪的邮箱，要到邮箱里设置开通STMP服务才可以用JAVAMAIL调用，默认增加了props.setProperty("mail.smtp.auth", "true"); 以及密码，还没测试不加这两个是否可行，下载下来里的代码默认都是没有执行这些的
