### ISSUE TITLE
使用问题请教 (报表设置好后，运行始终提示【未查询到相关数据】)

### ISSUE THREAD

**Issue by whelkman** [Baidu-ecom/bi-platform#120]
从github.com 获取了branch_1.4.0的代码后编译并且能够正常安装、启动。但是在设置了一个报表后，即始终被提示无法获取到数据。

运行环境明细如下：
1. 操作系统Windows7 64位， 没有redis
2. 本机安装了mysql, 并且有一张主数据表 test_sum_data, 包含3个字段 sum_date(日期)、bal_amt(数值)、act_bal_amt(数值), 有3条有效数据
3. 配置了一个报表，只使用一个‘时间维度',  选被被关联表【内置表】,选择时间字段【sum_date】 粒度【日】,时间格式【yyyy-MM-dd】与 sum_date字段的值格式相同

按上述配置，即始终无法查询到库表test_sum_data中的3条数据.
整个平台的安装启动，参照http://my.oschina.net/biplatform/blog上的博文完成。

我在想是否是因为环境中没有redis 造成的？

下面这条是tesseract的日志信息：
[2015-06-01 18:21:40693 DEBUG]--pool-3-thread-1--DefaultListableBeanFactory: Returning cached instance of singleton bean 'node' 
看上去在运行这个报表时，tesseract 已经接收到了请求，并返回了结果。

另外，两个配置文件的redis相关的配置信息如下,
【application.proppertis】
################################################################################################
# redis cache config
################################################################################################
config.redis.usePool=true
config.redis.password=biplatform
#spring.redis.port=
config.redis.poolConfig.max-idle=8
config.redis.poolConfig.min-idle=0
config.redis.poolConfig.max-active=8
config.redis.poolConfig.max-wait=-1
################################################################################################
#default use redis
################################################################################################
config.redis.active=false

################################################################################################
#mark if this instance is dev
################################################################################################
#config.redis.dev=true

################################################################################################
#redis conifg proeprties
################################################################################################
config.redis.poolConfig.testOnReturn=true
config.redis.poolConfig.testWhileIdle=true
config.redis.poolConfig.testOnBorrow=true
config.redis.poolConfig.testOnCreate=true
config.redis.poolConfig.timeOut=1000

config.redis.topicName=silkroad_topic
config.redis.eventQueueName=silkroad_event_queue
config.redis.lockName=silkroad_lock

################################################################################################
# redis server config
################################################################################################
config.redis.sentinel.master=biplatform_master
config.redis.sentinel.nodes=localhost:8379

#hazelcast cluster config info
hazelcastServer.groupUserName=silkroad-group
hazelcastServer.groupPassword=silkroad
#hazelcastServer.mancenter.url=
hazelcastServer.mancenter.enable=false
hazelcastServer.members=127.0.0.1
hazelcastServer.portAutoIncrement=false
hazelcastServer.instanceName=silkroad-cluster

【 tesseract.properties】
 config.redis.usePool=true
config.redis.password=passwd
#spring.redis.port=
config.redis.poolConfig.max-idle=8
config.redis.poolConfig.min-idle=0
config.redis.poolConfig.max-active=8
config.redis.poolConfig.max-wait=-1

#default use redis
config.redis.active=false

#mark if this instance is dev
config.redis.dev=true

#config topic ,queue , lock name
config.redis.topicName=tesseract_topic
config.redis.eventQueueName=tesseract_event_queue
config.redis.lockName=tesseract_lock
config.redis.poolConfig.testOnReturn=true
config.redis.poolConfig.testWhileIdle=true
config.redis.poolConfig.testOnBorrow=true
config.redis.poolConfig.testOnCreate=true

#config cluster pre
config.redis.clusterPre=lijin
#config default cache exprie time, unit second, -1 never expire
config.redis.defaultExpire=-1
#config cache expire time, format   config.redis.cacheExpire.(cachename)=(expire seconds)
config.redis.cacheExpire.biplatform=1800
config.redis.sentinel.master=biplatform_master
config.redis.sentinel.nodes=ip:port

#hazelcast cluster config info
hazelcastServer.groupUserName=group
hazelcastServer.groupPassword=passwd
#hazelcastServer.mancenter.url=
hazelcastServer.mancenter.enable=false
hazelcastServer.members=127.0.0.1
hazelcastServer.portAutoIncrement=false
hazelcastServer.instanceName=tesseract-cluster

PS:
1. 由偿试了多次，都无法将截图上传，只能通过文字描述；
2. @david.wang(wangyuxue), 我前晚冒昧的向你的邮箱（sishuiliunian2004@163.com）中发了一封详细的带截图的邮件，请教这个问题。方便的话，请查看一下。

谢谢大家！

**Comment by wangyuxue** [comment]
@whelkman  你好。默认平台不需要redis支持。平台默认缓存在用hz。如无redis服务，启动时请添加-Dconfig.redis.active=false 参数设置

**Comment by wangyuxue** [comment]
此外，时间维度目前支持数据库中存储格式为yyyyMMdd格式

**Comment by whelkman** [comment]
偿试了，不全是数据库中日期字段存储格式的问题。我将数据日期字段的值全部改为yyyyMMdd格式后，运行报表，依然提示【没有查询到相关数据】。

于是我根据输出的运行日志，阅读了QueryDataResource.java 的代码，发现1045 catch(Throwable t) 中也可能会返回信息【没有查询到相关数据】，但这里没有输出异常信息到日志中。我在此增加了输出异常信息到日志文件的代码后，再次运行报表，发现这里的确抛出了异常信息。

异常信息为：com.baidu.rigel.biplatform.ac.util.ConfigInfoUtils.<clinit>(ConfigInfoUtils.java:52) 这里抛了空指针，而这里代码段为：
             String answerCoreConfFile = System.getProperty("ac.config.location");            
            properties = new Properties();
            inStream = new FileInputStream(answerCoreConfFile);
问题出在 answerCoreConfFile  这个变量并没有值，所以运行出现空指针异常；

但是很奇怪的是，我启动 designer的命令已经指定了 ac.config.location了，命令如下：
java -jar designer-1.4.0-SNAPSHOT.jar -Dserver.port=8090 -Dac.config.location=d:/biplatform/ac.properties

但是上面那代码的确无法获取到ac.config.location这个系统参数的值。

最后，我先暂时修改了ConfigInfoUtils.java的代码，将answerCoreConfFile 的值设为我本地环境上的ac.properties 文件的绝对路径，重新打包发布后，报表可以正常出现数据了。

目前还无法确定为何通过System.getProperty("ac.config.location"); 获取启动时设置的参数值。

**Comment by wangyuxue** [comment]
@whelkman  这个问题我们再进一步验证一下，感谢提醒！

**Comment by kisskevin** [comment]
同样无法通过 System.getProperty("ac.config.location"); 获得启动参数中指定的值，如-Dac.config.location=E:\baidu_bi\installed\ac.properties

**Comment by whelkman** [comment]
可以修改一下为 com.baidu.rigel.biplatform.ac.util.ConfigInfoUtils

增加一个静态常量定义 private static final String DEFAULT_AC_CONFIG_FILENAME="ac.properties";

然后在代码  String answerCoreConfFile = System.getProperty("ac.config.location");   下增加代码：
 if (null == answerCoreConfFile )
  {
            	answerCoreConfFile = System.getProperty("user.dir")+System.getProperty("file.separator")+DEFAULT_AC_CONFIG_FILENAME;
  }

 这样，只要 ac.properties 文件在你执行 designer启动命令的目录中，那无论 ac.config.location参数是否能取得值，都可以正常读取的 ac.properties文件.

**Comment by wangyuxue** [comment]
@whelkman 感谢你的建议，我们会考虑这样的方案，谢谢！

**Comment by sundongwen** [comment]
我也按照上面的进行配置的，也显示未查询到相关数据。后台报错，QueryDataResource：查询数据失败!

**Comment by wangyuxue** [comment]
你好，关于这个问题，已经在新版本中修正，如其他问题，最好能提供一下报错的日志信息
