### ISSUE TITLE
已经注册用户登录数据加载异常

### ISSUE THREAD

**Issue by ZhanPeng** [Baidu-ecom/bi-platform#127]
已经修改完毕管理员邮箱帐号密码，注册用户后，确认该用户使用线上模式。登录用户显示数据加载异常
http://192.168.1.183:8090/silkroad/null
Console:
UniversalContextSettingFilter:productLine in token is [username] and sessionId is null

bi-platform-1.4.0-RELEASE

**Comment by wangyuxue** [comment]
你好，这个问题已经修复，请更新一下代码。
错误原因：登陆跳转默认跳转到登陆之前访问页面。

解决办法：
访问设计器请从：
http://192.168.1.183:8090/silkroad/index.html
访问

**Comment by ZhanPeng** [comment]
test version:bi-platform-1.5.0-SNAPSHOT
result:success
