### ISSUE TITLE
v1.4.0_release_20150601 无法构建成功

### ISSUE THREAD

**Issue by lovewhll** [Baidu-ecom/bi-platform#129]
从maven构建提示信息来看是依赖了内部jar
<dependency>
		  <groupId>com.baidu.rigel.tmp.uc</groupId>
		  <artifactId>casclient</artifactId>
		  <version>1.0</version>
</dependency>

可否提供下解决方案？

**Comment by wangyuxue** [comment]
你好，1.4.0中不需要casclent的包，在构建过程中，可以将依赖删除即可。另推荐使用新版本build，新版本在解决原有bug基础上，对功能进行了增强

**Comment by lovewhll** [comment]
已解决，谢谢！
