### ISSUE TITLE
关于注册

### ISSUE THREAD

**Issue by Douzy75952** [Baidu-ecom/bi-platform#133]
三个jar已经全部编译且跑起来 , 注册的时候 提示send register message to Administrator happens exception, log也看不到信息, 不知道是哪里有问题?是缺少了什么组件么？
SMTP 及 mail 相关参数也已经设置

**Comment by Douzy75952** [comment]
~ 邮件已发送成功  ,  现在问题是发送了申请邮件后 要怎么开通？

**Comment by wangyuxue** [comment]
你查看邮件，点击开通服务及可以了。前提是你的服务外网能够访问到。后者你在本地启动，在本地通过邮件开通服务

**Comment by Douzy75952** [comment]
恩,那个table的A标签不是很明显 没有颜色标注,最后找到了。现在已经在线上跑了, 谢谢
Date: Sat, 25 Jul 2015 00:08:06 -0700

**Comment by wangyuxue** [comment]
感谢支持
