### ISSUE TITLE
【问题请教】HeadField结构如何理解？

### ISSUE THREAD

**Issue by joyyoj** [Baidu-ecom/bi-platform#134]
我下了代码，发现这个HeadField好复杂，各种树结构，不知道如何理解？谢谢。
另外，我发现对非字符类型支持的有些问题。例如fact table的字段各种dims都使用int类型的id，这样拼出来的sql就是 id in ('', '') 后面默认都是字符，导致sql出错。

**Comment by wangyuxue** [comment]
你好，HeadField实际上是一个树表结构，未配合多位下钻、旋转操作，headFied的根为整个表汇总节点的描述，headField的child实际上是与根对应的维度的当前层级的描述，headField的nodelist是对与当前维度较差的维度的描述。比如：
北京地区汇总  －－－ 2001年
                                   2002年
朝阳
海淀

北京地区即为HeadField的根，朝阳、海淀为child， 2001 2002 为nodeList，headField中的每个几点均可以认为是一个根。

**Comment by joyyoj** [comment]
感谢你的解答.不过还是不太理解，假如我的sql是
select country, net_type, sum(click), sum(view) from table group by country, net_type;
这样出来的应该是2个dim， 2个measure，那么measure都在col里。
但是country和net_type却是两个row，返回给前端的DataModel该如何设置呢？uniqueName/value、caption等该如何设置？谢谢

**Comment by wangyuxue** [comment]
country －－ nettype 汇总
国家1 －－ nettytype1
                   nettype2
国家2 －－同上
uniqueName为［维度名称].[成员名称] value为对应维度关联的外键值 ，每一行有一个nodeuniquename概念，为：{第一个维度uniqueName}.{第二个维度uniqueName}

**Comment by joyyoj** [comment]
感谢答复
