### ISSUE TITLE
如何替换执行引擎层

### ISSUE THREAD

**Issue by joyyoj** [Baidu-ecom/bi-platform#135]
我觉得平台提供的功能正是我想要的。只是目前OlapEngine层是tesseract，但我想直接使用MYSQL或者KYLIN之类的执行引擎层，如果直接用QueryServiceImpl会比较有问题。因为里面拼出来的SQL不是为这些存储做的优化。
另外，我看到branch1.6里面有palo的支持，据我了解palo就是一个olapengine的实现，提供mysql的接口。
我初步的想法是实现自己的QueryServiceImpl，应该就可以了，但是有些耦合。不知道你们是否会在这块架构或者模块上是否会有一些调整，比如把tesseract拆成两个模块，一个是plugin，一个是共用的，这样可以使得工程看起来更干净点。用户可以只需要实现一个plugin就将QuestionModel换成自定义的storage的执行计划。
另外，前端部分有一些hardcode，比如“汇总"这样的字眼。后续是否会改进一下？
谢谢。

**Comment by wangyuxue** [comment]
你好，感谢你的建议。你说的这个我们正在调整系统架构，调整之后，所有的执行引擎都会以plugin的方式注入系统，系统通过查询路由层决策究竟哪个引擎处理。
tesseract以后会作为与Palo、Mysql、甚至麒麟相同层次的Engine层。在Tesseract上层的路由层处理Engine层不能解决的计算因子以及相应的Engine的路由。
代码中硬编码的东西，后续会根据相应的ID，caption策略进行调整与优化
