### ISSUE TITLE
卡在确认用户注册了

### ISSUE THREAD

**Issue by hngggeee** [Baidu-ecom/bi-platform#147]
{"statusInfo":"open online service for user [hnggg] failed","status":1,"data":null,"properties":{}}，点邮件确认用户的线上注册，报这个错，实在是找不到原因啊

**Comment by hngggeee** [comment]
跟着代码查看到最终问题是在FileServerClient的doRequest方法里，这个方法返回的Respone一直都是[status : FAIL, message : failed, datas : null]，导致最终报错，这个方法里的代码看不太懂，请问下为什么

**Comment by hngggeee** [comment]
找到原因了，文件服务器没有开启，要先开启文件服务器

**Comment by wangyuxue** [comment]
多谢支持
