### ISSUE TITLE
用户操作手册出炉打不开，下载下来是破损文件

### ISSUE THREAD

**Issue by vblvbl** [Baidu-ecom/bi-platform#171]
https://github.com/Baidu-ecom/bi-platform/blob/branch_1.6.0/doc/BIPlatform%20V1.x%E7%94%A8%E6%88%B7%E6%93%8D%E4%BD%9C%E6%96%87%E6%A1%A3.pdf 这个pdf打不开

**Comment by vblvbl** [comment]
在源码包里 有下载好的文档

**Comment by wangyuxue** [comment]
这个应该是文件名的原因吧，改名试一下
