### ISSUE TITLE
什么时候提供详细的安装部署文档

### ISSUE THREAD

**Issue by ekekyn** [Baidu-ecom/bi-platform#175]
如题

**Comment by WalterInSH** [comment]
项目根目录的安装步骤似乎无法启动项目，并不友好，期待一个好的部署文档，感谢

**Comment by wangyuxue** [comment]
@WalterInSH 目前项目重构已经接近尾声，重构完毕之后随1.7发版一起提供，感谢关注

**Comment by WalterInSH** [comment]
@wangyuxue 感谢你们的工作！

**Comment by ekekyn** [comment]
真心希望新版的安装部署文档能够提供各个端口的说明及各系统之间的相关关系

**Comment by junweihuang** [comment]
@wangyuxue 关注中(*^__^*) ，期待有文档，queryrouter现在报错，还缺少applicationContext-queryrouter-plugin.xml文件

**Comment by wangyuxue** [comment]
@junweihuang  感谢关注，我们会尽量排查，解决问题
