### ISSUE TITLE
按月分析的时候不能按照选择的日期显示数据

### ISSUE THREAD

**Issue by whan0216** [Baidu-ecom/bi-platform#181]
![image](https://cloud.githubusercontent.com/assets/2864347/12161442/c7e106e2-b530-11e5-8b4c-1cf74143cd82.png)
见图，时间已经选择15年的10月到12月，但是列表中展示的确是16年1月的数据

**Comment by ekekyn** [comment]
的确存在这个问题。后台数据已经获取到了，似乎是前台页面显示问题

**Comment by whan0216** [comment]
@ekekyn 这个问题什么时候可以修复？

**Comment by wangyuxue** [comment]
@whan0216 你好，这个问题我们已经修复了，会在近期提交代码，感谢关注

**Comment by whan0216** [comment]
ok 感谢

**Comment by wangyuxue** [comment]
@whan0216 感谢关注
