### ISSUE TITLE
透视表分页

### ISSUE THREAD

**Issue by junweihuang** [Baidu-ecom/bi-platform#185]
貌似分页现在做的还不是很完整吧，透视是不是就不用分页了，期待新版本解决我的疑问。现在情况是透视表中limit 1,100

**Comment by wangyuxue** [comment]
你好，透视表是不支持分页功能的，你看到的limit 100 是在设计器中为提高设计速度，进行的优化，报表发布之后查询，是不存在limit 100的

**Comment by junweihuang** [comment]
是的，当我看到代码判断之后，我就把问题关闭了嘿嘿。但是还有一个问题，为什么只有palo有聚合查询，而其它的都没有聚合查询呢，是不是考虑到普通的数据库计算效率没有BI中的java8计算快呢？但是没有聚合查询，查出来的数据量是比较大的。



junweitoee@sina.com
 
发件人： david.wang
发送时间： 2016-01-19 10:15
收件人： Baidu-ecom/bi-platform
抄送： junweihuang
主题： Re: [bi-platform] 透视表分页 (#185)
你好，透视表是不支持分页功能的，你看到的limit 100 是在设计器中为提高设计速度，进行的优化，报表发布之后查询，是不存在limit 100的

**Comment by wangyuxue** [comment]
@junweihuang 是的，在大数据量下，mysql的计算能力表现不是很好
