### ISSUE TITLE
发布后的报表 能实现嵌入到自己工程里面吗 

### ISSUE THREAD

**Issue by huojg** [Baidu-ecom/bi-platform#2]
发布后的报表 能实现嵌入到自己工程里面吗 不用iframe嵌入  直接拿到报表图 有不是iframe嵌入的解决方案吗

**Comment by wangyuxue** [comment]
通过url的方式访问报表。可以通过render的方式渲染

**Comment by gsky3204** [comment]
现在无法下载到源码了，请问你之前下载好的一些资料可以共享给我下吗，谢谢。

**Comment by benrennanshen** [comment]
请问你们程序如何运行的，能发个资料链接给我吗？

**Comment by wangyuxue** [comment]
请访问 https://github.com/baidu/BIPlatform 查看最新的部署文档，这里不在更新
