### ISSUE TITLE
最近又没动静了，在憋大招吗

### ISSUE THREAD

**Issue by 305277391** [Baidu-ecom/bi-platform#203]
最近又没动静了，在憋大招吗。

**Comment by wangyuxue** [comment]
@305277391  现在在做回归测试，回归测试之后会release一版，新版在功能上有很多增强

**Comment by 305277391** [comment]
@wangyuxue 哥们大概几号呀，我想在新版的基础上开始使用和研究。要不要先发一版，我们一起测试呀。
