### ISSUE TITLE
问题请教，请问bi platform 和saiku+mondrian相比优势在什么地方

### ISSUE THREAD

**Issue by slungzr** [Baidu-ecom/bi-platform#204]
问题请教，请问bi platform 和saiku+mondrian相比优势在什么地方

**Comment by 305277391** [comment]
@slungzr    国产的会有很多中文文档，更容易学习。期待呀。

**Comment by totyumengr** [comment]
可以说bi-platform是借鉴过saiku+mondrian的。很长时间以前我们开始在架构上做大量的改造，
bi-platform是在百度内部生产环境中部署的。

**Comment by smallgoldstone** [comment]
感觉百度开源的力度不算大，这方面不如阿里

**Comment by totyumengr** [comment]
是的，希望未来能有更多的同学愿意为开源社区贡献。

**Comment by xiaomingchen** [comment]
建个沟通群什么的吧

**Comment by 305277391** [comment]
是啊，建个群吧。

**Comment by lijin0501** [comment]
我看有个QQ群，是其它网友建的，群号：149225568
