### ISSUE TITLE
能否提供Docker Image

### ISSUE THREAD

**Issue by WalterInSH** [Baidu-ecom/bi-platform#207]
Hi,
为了简化安装过程，规范安装过程，能否提供一个官方的 Docker Image？

这对于那些想要快速尝试bi-platform的人来说也是很有吸引力的

**Comment by wangyuxue** [comment]
感谢关注，目前暂时未有计划支持docker

**Comment by panxinyang2014** [comment]
@wangyuxue 能否提供示例数据库脚本呢？ 见 #206

**Comment by WalterInSH** [comment]
@wangyuxue 好的，十分感谢你们的工作
