### ISSUE TITLE
报表预览时提示seed.js文件不存在

### ISSUE THREAD

**Issue by bobqiu** [Baidu-ecom/bi-platform#208]
http://localhost:8090/silkroad/new-biplatform/asset/seed.js?action=display&t=1461656110081

Failed to load resource: the server responded with a status of 404 (Not Found)

源码以后还会更新吗？

**Comment by phphappy** [comment]
1.6的版本好用

**Comment by phphappy** [comment]
可以下载一个seed.js

**Comment by huojg** [comment]
@wangyuxue @phphappy  seed.js 下载地址有么？放在这个/silkroad/new-biplatform/asset/seed.js 这个路径下就可以了吗 代码有改的地方吗？
