### ISSUE TITLE
下一个版本什么时候更新呀？

### ISSUE THREAD

**Issue by 305277391** [Baidu-ecom/bi-platform#209]
下一个版本什么时候更新呀？

**Comment by wangyuxue** [comment]
@305277391  感谢关注，由于项目原因，BIPlatform暂停一段时间更新。

**Comment by totemp** [comment]
@wangyuxue 那有无计划呀？还有外面的资料太少了，这不利于产品的推广呀。

**Comment by brandom-iava** [comment]
@wangyuxue  这么久没动静了，发现你们这个项目非常不错，项目还会继续吗？

**Comment by wangyuxue** [comment]
感谢关注！项目会继续的。由于现在比较忙和公司内部事务，暂时未抽出时间继续该项目，在明年的规划中，我们会考虑继续的。
