### ISSUE TITLE
那个分支是可用的？

### ISSUE THREAD

**Issue by jonahLD** [Baidu-ecom/bi-platform#211]
你好我clone了2.0的分支，但是mvn install 项目 tesseract及designer时，均报错。
`[ERROR] Failed to execute goal on project designer: Could not resolve dependencies for project com.baidu.rigel.biplatform:designer:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:schedule:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:common-api:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:model:jar:2.0.0-SNAPSHOT: Could not find artifact com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException`

`[ERROR] Unknown lifecycle phase "intall". You must specify a valid lifecycle phase or a goal in the format <plugin-prefix>:<goal> or <plugin-group-id>:<plugin-artifact-id>[:<plugin-version>]:<goal>. Available lifecycle phases are: validate, initialize, generate-sources, process-sources, generate-resources, process-resources, compile, process-classes, generate-test-sources, process-test-sources, generate-test-resources, process-test-resources, test-compile, process-test-classes, test, prepare-package, package, pre-integration-test, integration-test, post-integration-test, verify, install, deploy, pre-clean, clean, post-clean, pre-site, site, post-site, site-deploy. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LifecyclePhaseNotFoundException`

**Comment by gclsoft** [comment]
@jonahLD Me,too. Have you solved it?

**Comment by jonahLD** [comment]
@gclsoft no，

**Comment by wangyuxue** [comment]
1.7.0 is the newest release version.  @gclsoft
