### ISSUE TITLE
请教一个问题，为什么我在启动tesseract时，tesseract服务不找自己的tesseract.properties中配置的sever.port端口，而是使用designer的配置文件application.properties呢，这样导致两个服务使用同一个端口，bind发生错误了

### ISSUE THREAD

**Issue by fengrb321** [Baidu-ecom/bi-platform#214]
在tesseract启动命令中，直接使用-Dserver.port=端口，也不生效，仍然会使用application.properties中的配置信息,我用的是bi-platform2.0版本的，我这么样才能够让tesseract服务找自己的tesseract.properties配置信息。

**Comment by shangqingbai** [comment]
我也遇到相同情况了，搞不清怎么回事。

**Comment by wangyuxue** [comment]
@fengrb321  将-Dserver.port=端口放到启动参数的第一个位置
