### ISSUE TITLE
1.6的版本注册用户失败FileServerClient: successfuly recieve message from file server [status : FAIL, message : 请求路径不存在, datas : {result=fail, msg=请求路径不存在}]

### ISSUE THREAD

**Issue by gclsoft** [Baidu-ecom/bi-platform#217]
windows 7上,C:\report目录有创建,但还是注册用户失败FileServerClient: successfuly recieve message from file server [status : FAIL, message : 请求路径不存在, datas : {result=fail, msg=请求路径不存在}]

**Comment by gm504117608** [comment]
你这个问题处理了吗？我也遇到这个问题了

**Comment by gm504117608** [comment]
你好问一下你这个问题是怎么处理的呢？我现在也遇到了相同的问题。
