### ISSUE TITLE
mvn install 问题

### ISSUE THREAD

**Issue by z328502560** [Baidu-ecom/bi-platform#219]
系统：UBUNTU 16.04LTS 
JDK：1.8.0_91
MAVEN：3.3.9
filesever 成功编译
其余两个编译失败
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.931 s
[INFO] Finished at: 2016-07-19T18:00:17+08:00
[INFO] Final Memory: 12M/147M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project designer: Could not resolve dependencies for project com.baidu.rigel.biplatform:designer:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:schedule:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:common-api:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:model:jar:2.0.0-SNAPSHOT: Could not find artifact com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR] 

[INFO] Total time: 1.290 s
[INFO] Finished at: 2016-07-19T18:51:27+08:00
[INFO] Final Memory: 16M/208M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project tesseract: Could not resolve dependencies for project com.baidu.rigel.biplatform:tesseract:jar:2.0.0-SNAPSHOT: The following artifacts could not be resolved: com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:model:jar:2.0.0-SNAPSHOT, com.baidu.rigel.biplatform:parser:jar:0.0.1-SNAPSHOT: Could not find artifact com.baidu.rigel.biplatform:cache:jar:2.0.0-SNAPSHOT -> [Help 1]
[ERROR]

**Comment by binggebest** [comment]
win10 下也出现了这样的问题  解决方式 将bi-platform 里执行mvn install 之后 可以构建 tesseract 之后 构建 bi-platform 里的common-api 和schedule (除designer之外的其他) 构建之后 可以构建designer

**Comment by z328502560** [comment]
现在是tesseract和designer均无法构建成功啊，只有filesever能够构建

**Comment by binggebest** [comment]
我在win10 下也是这样的情况  你回到biplatform 目录下 执行mvn install 之后你再 构建tesseract  就应该可以了 但是designer仍然无法构建  然后你再单独构建 common-api 和schedule  之后再构建designer 就可以了  应该是 designer 需要其他的所有都构建成功之后才能构建

**Comment by z328502560** [comment]
感谢帮助，问题已解决，需要按照一定顺序进行构建才能成功，参照：https://github.com/Baidu-ecom/bi-platform/issues/163

**Comment by caoevan** [comment]
我按照如下顺序还是没有解决：
（我在win10 下也是这样的情况 你回到biplatform 目录下 执行mvn install 之后你再 构建tesseract 就应该可以了 但是designer仍然无法构建 然后你再单独构建 common-api 和schedule 之后再构建designer 就可以了 应该是 designer 需要其他的所有都构建成功之后才能构建）
在biplatform 目录下 执行mvn install 
报：
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[55,21] 非法的表达式开始
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[55,24] 非法的表达式开始
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[55,26] 非法的表达式开始
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[55,27] 需要';'
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[56,18] 不是语句
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[56,24] 需要';'
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[68,10] 非法的类型开始
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[68,11] 需要';'
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[68,12] 方法声明无效; 需要返回类型
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[69,17] 需要<标识符>
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[69,18] 非法的类型开始
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[73,12] 需要class, interface或enum
[ERROR] /D:/biplatform/cache/src/main/java/com/baidu/rigel/biplatform/cache/redi
s/listener/RedisQueueListener.java:[75,5] 需要class, interface或enum
[INFO] 13 errors
