### ISSUE TITLE
com.baidu.rigel.biplatform.queryrouter.queryplugin.plugins.druid.sql不存在

### ISSUE THREAD

**Issue by jonahLD** [Baidu-ecom/bi-platform#221]
使用 branch 2.0.0，mvn install时，出现如下错误：
`[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project queryrouter: Compilation failure: Compilation failure: [ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/queryplugin/utils/QueryHandlerBuilder.java:[18,76] 程序包com.baidu.rigel.biplatform.queryrouter.queryplugin.plugins.druid.sql不存在 [ERROR] /D:/bi-platform-branch_2.0.0/queryrouter/src/main/java/com/baidu/rigel/biplatform/queryrouter/queryplugin/utils/QueryHandlerBuilder.java:[165,37] 找不到符号 [ERROR] 符号: 类 DruidSqlExpression [ERROR] 位置: 类 com.baidu.rigel.biplatform.queryrouter.queryplugin.utils.QueryHandlerBuilder [ERROR] -> [Help 1]`

该如何解决？

**Comment by binggebest** [comment]
注释掉 QueryHandlerBuilder.java 18 行的包以及下面引用到的代码

**Comment by luowenlei** [comment]
此问题已经修复，更新2.0的版本。
