### ISSUE TITLE
下钻功能有问题 有响应数据 显示表格为未查询到数据

### ISSUE THREAD

**Issue by huojg** [Baidu-ecom/bi-platform#222]
下钻功能有问题 有响应数据 显示表格为未查询到数据

**Comment by binggebest** [comment]
我也遇到这问题 至今未解决  你的维表结构是和手册里的一样不

**Comment by wangyuxue** [comment]
你好，这个问题是由于前端升级导致。配置报表时请访问新的首页 newIndex.html配置。

**Comment by huojg** [comment]
@wangyuxue 你好 newIndex.html这个文件里没有多少内容 可以说一下具体怎么去访问newIndex.html吗

**Comment by huojg** [comment]
@wangyuxue 你好下钻这个问题 具体的帮我指导一下吧？

**Comment by wangyuxue** [comment]
@huojg 前端代码已经上传，从2.0分支重新拉一下代码
