### ISSUE TITLE
ServerUtils: properties conf at : "server.queryrouter.systemcode" or "server.queryrouter.systemkey"   is null

### ISSUE THREAD

**Issue by ljjiang** [Baidu-ecom/bi-platform#223]
按照BIPlatform V1.x用户操作文档的demo，创建报表的时候designer控制台中显示这个错误，怎么解决？
附：配置和运行方式参考的是 ：http://my.oschina.net/biplatform/blog/412942

**Comment by wowojyc** [comment]
@ljjiang 这个缺少配置，请参考http://my.oschina.net/iwowojyc/blog/727923

**Comment by ljjiang** [comment]
@wowojyc ,  ok，我试试，非常感谢!!
