### ISSUE TITLE
不显示图例 调试哪个文件

### ISSUE THREAD

**Issue by huojg** [Baidu-ecom/bi-platform#227]
![qq 20161027191557](https://cloud.githubusercontent.com/assets/20555480/19765324/489323de-9c7a-11e6-9a87-97a09d3d5f68.png)

**Comment by wangyuxue** [comment]
需要确认维度、指标是否设置完全。如设置完全，建议拖拽一下图形大小，重新渲染一下。
Ps：最好用chrome打开，目前前端代码是压缩的，基于echarts，调试比较困难。

**Comment by phoenixisland** [comment]
现在用index-local.html倒是可以看为压缩的代码，但是好像代码比较旧，至少比压缩的代码
另外压缩规则和压缩工具是否可以介绍一下

**Comment by wangyuxue** [comment]
你好，目前前端代码由于授权原因，未全部开源。前端采用的是vue的框架。
