### ISSUE TITLE
修改几个工程的端口都在几个文件中修改 需要注意的地方有哪些？

### ISSUE THREAD

**Issue by huojg** [Baidu-ecom/bi-platform#228]
修改几个工程的端口都在几个文件中修改 需要注意的地方有哪些？

**Comment by wangyuxue** [comment]
每个项目都有一个application.properties 文件，在里面指定server.port或者在启动的时候，用-Dserver.port指定端口均可。文件服务器与queryrouter的端口需要与配置文件中配置的一致

**Comment by phoenixisland** [comment]
并不是所有的项目中都有application.properties。
另外是否有文档说明一下每个application.properries中的配置属性说明
现在关于BIPlatform的文档太少了

**Comment by wangyuxue** [comment]
感谢关注，我们会注意并跟进这个问题
