### ISSUE TITLE
designer中js疑问

### ISSUE THREAD

**Issue by wangboshi2015** [Baidu-ecom/bi-platform#233]
发现/designer/src/main/resources/public/silkroad/asset目录下的js文件都是混淆的，这是否为构建目录，源文件来自他处？
/designer/src/main/resources/public/silkroad/**new-biplatform**/asset这个文件夹是否也是构建目录？

**Comment by wangyuxue** [comment]
@wangboshi2015 我们会考虑开源前端代码，需要fe团队授权，正在协商中

**Comment by wangboshi2015** [comment]
@wangyuxue 谢谢，希望早日看到完全开源的产品，也希望新版本早日出炉
