### ISSUE TITLE
预览、保存、关闭功能

### ISSUE THREAD

**Issue by nayooyoo** [Baidu-ecom/bi-platform#57]
a)	三个功能全放置到全局工具栏上，点击预览后，弹出新页面展现当前配置的报表，不出现当前点击发布后的弹框
b)	点击保存后，如当前效果给出提示
c)	关闭按钮放置在工具栏最右侧，如果没有保存点击了关闭，给用户提示是否需要保存，关闭后，到报表列表页面

**Comment by weiboxue** [comment]
done
