### ISSUE TITLE
注册时验证码一直提示错误

### ISSUE THREAD

**Issue by nayooyoo** [Baidu-ecom/bi-platform#61]
刚才注册的时候，提示验证码一直不正确，后来得知这个验证码区分大小写。
希望不要这么任性还没有提示，导致用户一直傻傻的输入验证码，但就是不正确。
方案一：不区分大小写
方案二：明确提示区分大小写

**Comment by totyumengr** [comment]
顶一个，我也这么觉得！~

**Comment by lijin0501** [comment]
同顶。不区分大小写，太弱了！

**Comment by weiboxue** [comment]
done
